export const DEFAULT = 'DEFAULT';
export const TEXT_BODY_UPDATE = 'TEXT_BODY_UPDATE';
export const TEXT_INPUT_CHANGE = 'TEXT_INPUT_CHANGE';
export const TAB_KEY = 'TAB_KEY';
export const UPDATE_ACTIVETREE = 'UPDATE_ACTIVETREE';
export const INSERT_BRANCH = 'INSERT_BRANCH';
export const REMOVE_BRANCH = 'REMOVE_BRANCH';
export const MOVE_BRANCH = 'MOVE_BRANCH';
export const CLOSE_BRANCH = 'CLOSE_BRANCH';
export const OPEN_BRANCH = 'OPEN_BRANCH';

export const TOGGLE_SEARCH_BAR_DISPLAY = 'TOGGLE_SEARCH_BAR_DISPLAY';
export const SHOW_SEARCH_BAR = 'SHOW_SEARCH_BAR';
export const HIDE_SEARCH_BAR = 'HIDE_SEARCH_BAR';

export const SEARCH_PREV = 'SEARCH_PREV';
export const SEARCH_NEXT = 'SEARCH_NEXT';

export const UPDATE_SEARCH_INPUT = 'UPDATE_SEARCH_INPUT';
export const UPDATE_REPLACE_INPUT = 'UPDATE_REPLACE_INPUT';
export const UPDATE_BRANCH_CLICK_COUNT = 'UPDATE_BRANCH_CLICK_COUNT'


export const GET_FILENAME = 'GET_FILENAME';
